name: 'publish-ppa-package'
description: 'Publish a PPA package'
branding:
  color: orange
  icon: package
inputs:
  git_repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  git_token:
    description: 'GitHub token to use'
    default: ${{ github.token }}
  ppa_package:
    description: 'Package name'
    required: true
  ppa_repository:
    description: 'The PPA repository, e.g., "yuezk/globalprotect-openconnect"'
    required: true
  upstream_version:
    description: 'Upstream version.'
    required: true
  gpg_private_key:
    description: 'GPG private key exported as an ASCII armored version or its base64 encoding'
    required: true
  gpg_passphrase:
    description: 'Passphrase of the GPG private key'
    required: false
  deb_email:
    description: 'The email address of the maintainer'
    required: true
  deb_fullname:
    description: 'The full name of the maintainer'
    required: true
  series:
    description: 'The series to which the package will be published, separated by space. e.g., "bionic focal"'
    required: false
  revision:
    description: 'The revision of the package'
    required: false
    default: '1'

runs:
  using: docker
  image: Dockerfile
